# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foreman-fapolicyd.spec

# add or remove files that should be synced
files_to_sync:
    - foreman-fapolicyd.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: foreman-fapolicyd
# downstream (Fedora) RPM package name
downstream_package_name: foreman-fapolicyd

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/foreman-fapolicyd/foreman-fapolicyd.spec -O foreman-fapolicyd.spec"
  get-current-version: "cat VERSION"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - rhel-8
      - rhel-9

srpm_build_deps:
  - wget
